"""governova_handoff — per-stage engineer handoff briefs.

Operationalizes the handoff step of `protocols/build-lifecycle.md`: Governova generates
the brief for a build stage from the compiled index, so the engineer starts grounded —
what to build, why (the governing constitution + standards), where it sits in the
dependency-first order, what it depends on (prior stages are stable contracts), and what
not to touch. The brief is the engineer's single source of guidance; they may edit it and
Governova refines it.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from governova_compile.discovery import resolve_repo_root
from governova_compile.writer import load_active_index

# The dependency-first build order from protocols/build-lifecycle.md §1.
# Each stage names the constitutions that govern it and the stages it builds upon.
STAGES: dict[str, dict[str, Any]] = {
    "foundation": {"order": 0, "constitutions": ["C00", "C01"], "depends_on": []},
    "database": {"order": 1, "constitutions": ["C05"], "depends_on": ["foundation"]},
    "auth": {"order": 2, "constitutions": ["C03"], "depends_on": ["foundation", "database"]},
    "backend": {"order": 3, "constitutions": ["C02"], "depends_on": ["foundation", "database", "auth"]},
    "frontend": {"order": 4, "constitutions": ["C04"], "depends_on": ["foundation", "database", "auth", "backend"]},
    "quality": {"order": 5, "constitutions": ["C07", "C08"], "depends_on": ["backend", "frontend"]},
    "product": {"order": 6, "constitutions": ["C09", "C10"], "depends_on": ["quality"]},
}

STAGE_ORDER = sorted(STAGES, key=lambda s: STAGES[s]["order"])


@dataclass(frozen=True)
class AreaBrief:
    constitution_id: str
    name: str
    standards: int
    anti_patterns: int
    key_standards: list[tuple[str, str]] = field(default_factory=list)  # (id, title)


@dataclass(frozen=True)
class Handoff:
    stage: str
    order: int
    depends_on: list[str]
    areas: list[AreaBrief]


def stages() -> list[str]:
    return list(STAGE_ORDER)


def build_handoff(stage: str, root: Path | None = None) -> Handoff:
    """Build the handoff for a build stage. Raises KeyError for an unknown stage."""
    key = stage.strip().lower()
    if key not in STAGES:
        raise KeyError(f"unknown stage '{stage}'. Known: {', '.join(STAGE_ORDER)}")
    spec = STAGES[key]
    r = root or resolve_repo_root()
    index = load_active_index(start=r)
    by_id = {c.id: c for c in index.constitutions}

    areas: list[AreaBrief] = []
    for cid in spec["constitutions"]:
        c = by_id.get(cid)
        if c is None:
            continue
        # "Key standards" = the first few highest-priority standards, as orientation.
        key_std = [(s.id, s.title) for s in c.standards[:6]]
        aps = sum(len(s.anti_patterns) for s in c.standards)
        areas.append(
            AreaBrief(
                constitution_id=c.id,
                name=c.name,
                standards=len(c.standards),
                anti_patterns=aps,
                key_standards=key_std,
            )
        )
    return Handoff(stage=key, order=spec["order"], depends_on=list(spec["depends_on"]), areas=areas)


def to_markdown(h: Handoff) -> str:
    govern = ", ".join(f"{a.constitution_id} ({a.name})" for a in h.areas) or "—"
    deps = ", ".join(h.depends_on) or "none — this is the foundation"
    later = [s for s in STAGE_ORDER if STAGES[s]["order"] > h.order]
    lines = [
        f"# Engineer Handoff — {h.stage.capitalize()} stage",
        "",
        f"*Generated by Governova from the compiled index · build order position {h.order} "
        f"of {len(STAGE_ORDER) - 1} · governed by {govern}*",
        "",
        "## What you are building",
        "",
        f"The **{h.stage}** stage, governed by {govern}. Build it to those standards at the "
        "smallest correct scope (S1.107 — the simplest correct solution).",
        "",
        "## What you must NOT touch",
        "",
        f"- The stages you build upon are **stable contracts**: {deps}. Do not modify them — "
        "consume them. A change there is a separate, reviewed task.",
        f"- Later stages ({', '.join(later) or 'none'}) are not yours; do not pre-build them.",
        "",
        "## Why — the standards that govern this stage",
        "",
    ]
    for a in h.areas:
        lines.append(f"### {a.constitution_id} — {a.name}  ·  {a.standards} standards, {a.anti_patterns} anti-patterns")
        for sid, title in a.key_standards:
            lines.append(f"- `{sid}` — {title}")
        lines.append("")
    lines += [
        "## The loop you must complete (protocols/build-lifecycle.md §2)",
        "",
        "**Build → Harden → Self-review → External-review → Handoff.** The stage is done when "
        "it passes the loop, not when it is built. A *different* engineer must review what you "
        "build — to catch what you cannot see.",
        "",
        "## Principles",
        "",
        "- *Make it exist first, then make it beautiful later.*",
        "- *Build smart, not hard* — the simplest, lightest correct solution is the required one.",
        "",
        "---",
        "",
        "*Edit this handoff if something is missing; Governova will refine it to stay consistent "
        "with the constitution. No stage is built without one.*",
    ]
    return "\n".join(lines)


__all__ = ["STAGES", "AreaBrief", "Handoff", "build_handoff", "stages", "to_markdown"]
