"""governova_onboard.propose — the profile, written for a human to accept.

`governance/project.toml` decides which standards apply, so a wrong profile
distorts every number downstream — and an adopter reading a baseline will believe
the numbers well before they think to question the profile that produced them.

That asymmetry is why this module renders a proposal rather than a file. The
profile is **never written without an explicit instruction**, and when it is
written it carries its own reasoning: every value names the file it was derived
from, and every field that could not be derived is present as a commented
placeholder saying what leaving it out costs.

A commented placeholder is deliberate over an omitted key. A field that is simply
absent from a generated file is a field nobody ever fills in, and the two fields
this cannot derive — domain and phase — are precisely the two that decide how
much of the constitution applies.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from governova_project import PROJECT_RELATIVE_PATH

from governova_onboard.detect import Detection

# The proposal declares a profile and nothing else. It never proposes a
# `[[satisfied]]` entry: coverage is a ratio, and a tool that arrives at a
# repository and grants it evidence it has not demonstrated is inflating the
# number it exists to report.
_HEADER = """\
# Governova — project profile (PROPOSED, not yet accepted)
#
# Generated by `governova onboard` on {today} from {source}.
# Review every line before this is treated as true: applicability is derived from
# this file, so a wrong value here is a wrong number in every report that follows.
#
# Two fields below are commented out because no scan can settle them. They are
# left in place, rather than omitted, because an absent field is one nobody fills
# in — and these two decide how much of the constitution applies.
#
# Nothing here declares a standard satisfied. Evidence is something a repository
# demonstrates; it is not something an onboarding tool grants it on arrival.
"""

_DOMAIN_NOTE = """\
# Layer 4 domain(s) — NOT DETECTED, and not detectable. A domain states which
# business a system is in, and a payments ledger and a lesson planner can be
# structurally identical. While this is unset, no sector standards are counted.
# Valid values: {domains}
# domains = []
"""

_PHASE_NOTE = """\
# Lifecycle phase reached — NOT DETECTED, and not detectable. Code on disk cannot
# distinguish "phase 3 reached" from "phase 1, written by someone thorough".
# While this is unset every phase's standards are counted, which is the widest
# reading and therefore the hardest score — the safe direction to be wrong in.
# phase = 3
"""

_NO_STACK_NOTE = """\
# stacks — NOT DETECTED. No manifest this engine recognises was found, so the
# stack could not be read from a declaration and was not inferred from file
# extensions. Standards scoped to a named stack are currently excluded on that
# undetected basis, which narrows the applicable set: set this before trusting
# any coverage figure.
# stacks = []
"""


def _toml_string(value: str) -> str:
    """A TOML basic string. JSON's escaping is a subset TOML accepts verbatim."""
    return json.dumps(value)


def _stack_block(detection: Detection) -> str:
    if not detection.stacks:
        return _NO_STACK_NOTE
    sources = {s.value: s.evidence for s in detection.of("stack")}
    lines = [
        "stacks = [{}]".format(", ".join(_toml_string(s) for s in detection.stacks)),
    ]
    for stack in detection.stacks:
        lines.append(f"#   {stack} — from {sources[stack]}")
    return "\n".join(lines) + "\n"


def render_profile(
    detection: Detection, *, domains: tuple[str, ...] = (), source: str = ""
) -> str:
    """The proposed `governance/project.toml`, as text.

    `domains` is the list of ratified Layer 4 domain ids, quoted into the
    commented placeholder so the reviewer does not have to go and look them up.
    `source` is the scanned path, recorded so the proposal says where it came
    from.

    The result is TOML and must be displayed as TOML. Printing it through a
    console that parses square brackets as markup silently deletes `[project]`,
    which is how the first version of this offered a reviewer a file that would
    not parse if they copied it.
    """
    parts = [
        _HEADER.format(today=date.today().isoformat(), source=source or detection.name or "."),
        "\n[project]\n",
        f"name = {_toml_string(detection.name)}\n",
        _stack_block(detection),
        "\n",
        _DOMAIN_NOTE.format(domains=", ".join(domains) if domains else "see `governova domains`"),
        "\n",
        _PHASE_NOTE,
    ]
    return "".join(parts)


class ProfileExistsError(FileExistsError):
    """Raised rather than overwriting a profile somebody already authored.

    An existing profile is a human decision about which standards apply. Silently
    replacing it with a generated guess would discard the strongest evidence in
    the repository about what the repository is.
    """


def accept(root: Path, text: str) -> Path:
    """Write the proposal to `governance/project.toml`. Never overwrites.

    Returns the path written. Raises `ProfileExistsError` when one is already there.
    """
    destination = root / PROJECT_RELATIVE_PATH
    if destination.exists():
        raise ProfileExistsError(
            f"{PROJECT_RELATIVE_PATH} already exists — refusing to overwrite a profile "
            f"that was authored deliberately. Delete it first if it should be replaced."
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(text, encoding="utf-8")
    return destination


__all__ = ["ProfileExistsError", "accept", "render_profile"]
