"""Generate the standalone `governova_types` Python package from schema.py.

The published `governova-types` package must not depend on the build tooling
(`governova`, the engine distribution). So we vendor the schema models into it:
read schema.py, prepend a generated-file banner, and write it as
`governova_types/models.py`. The schema remains the single source of truth —
codegen propagates it.

**A complete distribution, not just modules.** The generated tree is a uv
workspace member and is intended for PyPI, so it needs a `pyproject.toml` and a
`py.typed` marker. Emitting only the modules left a member directory uv could not
resolve, which broke `uv sync` for anyone who had run codegen — invisible in CI,
because a fresh checkout has no such directory at all.

**Everything emitted here is deterministic.** No timestamps, no commit SHAs,
sorted exports. The output is committed and drift-checked in CI exactly like
`compiled/constitution.json`, and a generator whose output varies between runs
cannot be drift-checked.
"""

from __future__ import annotations

from pathlib import Path

from governova_compile.schema import SCHEMA_VERSION

_BANNER = '''"""Governova — compiled constitutional index models.

DO NOT EDIT. Generated from scripts/governova_compile/schema.py by
`governova-codegen`. Edit the source schema, then re-run codegen.
"""
'''

_INIT = '''"""Generated Governova types. Do not edit — run `uv run governova-codegen`."""

from governova_types.models import (
    ADR,
    SCHEMA_VERSION,
    AntiPattern,
    CompiledIndex,
    Constitution,
    DocumentHeader,
    DocumentStatus,
    FrameworkPrimitive,
    Implementation,
    ImplementationBinding,
    IntegrityIssue,
    IntegrityReport,
    Phase,
    Practice,
    Priority,
    Reference,
    Runbook,
    Severity,
    Standard,
    export_json_schema,
)

__all__ = [
    "ADR",
    "SCHEMA_VERSION",
    "AntiPattern",
    "CompiledIndex",
    "Constitution",
    "DocumentHeader",
    "DocumentStatus",
    "FrameworkPrimitive",
    "Implementation",
    "ImplementationBinding",
    "IntegrityIssue",
    "IntegrityReport",
    "Phase",
    "Practice",
    "Priority",
    "Reference",
    "Runbook",
    "Severity",
    "Standard",
    "export_json_schema",
]
'''


def _manifest() -> str:
    """The generated package's `pyproject.toml`.

    Versioned by `SCHEMA_VERSION` rather than independently: this package *is* the
    schema, so a consumer pinning `governova-types` is pinning the index shape it
    can read. An independent version number would be a second thing to remember
    to bump, and it would drift.

    `pydantic` is the only dependency — deliberately not `governova`, so consuming
    the types never drags in the build tooling.
    """
    return f'''# DO NOT EDIT. Generated by `governova-codegen`.
# Version tracks SCHEMA_VERSION in scripts/governova_compile/schema.py.
[project]
name = "governova-types"
version = "{SCHEMA_VERSION}"
description = "Typed models for the Governova compiled constitutional index"
readme = "README.md"
requires-python = ">=3.12"
authors = [{{ name = "Maluleke Kurhula Success" }}]
license = {{ text = "MIT" }}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]
dependencies = ["pydantic>=2.9"]

[project.urls]
Homepage = "https://github.com/KSDRILL-SA/governova"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["governova_types"]
'''


_README = f"""# governova-types

Typed models for the Governova compiled constitutional index
(`compiled/constitution.json`).

**Generated — do not edit.** Emitted from
`scripts/governova_compile/schema.py` by `governova-codegen`. Edit the schema,
re-run codegen.

The version tracks the index schema version (currently `{SCHEMA_VERSION}`): pinning
this package pins the index shape your code can read.

```python
from governova_types import CompiledIndex

index = CompiledIndex.model_validate_json(Path("compiled/constitution.json").read_text())
```

Depends only on `pydantic` — never on the Governova engine.
"""


def generate_python_types(schema_source: Path, types_py_root: Path) -> Path:
    """Emit the complete `governova-types` distribution. Returns the models path."""
    pkg = types_py_root / "governova_types"
    pkg.mkdir(parents=True, exist_ok=True)

    source = schema_source.read_text(encoding="utf-8")
    # Replace the original module docstring (first triple-quoted block) with the banner.
    body = _strip_leading_docstring(source)
    (pkg / "models.py").write_text(_BANNER + "\n" + body, encoding="utf-8")
    (pkg / "__init__.py").write_text(_INIT, encoding="utf-8")
    # A typed package that ships no marker is untyped to its consumers (S1.49).
    (pkg / "py.typed").write_text("", encoding="utf-8")
    (types_py_root / "pyproject.toml").write_text(_manifest(), encoding="utf-8")
    (types_py_root / "README.md").write_text(_README, encoding="utf-8")
    return pkg / "models.py"


def generated_files(types_py_root: Path) -> dict[Path, str]:
    """Every path this generator owns, mapped to its expected content.

    Used by `--check` to detect drift without writing anything. Kept beside the
    writer so a new emitted file cannot be added without appearing here.
    """
    pkg = types_py_root / "governova_types"
    return {
        pkg / "__init__.py": _INIT,
        pkg / "py.typed": "",
        types_py_root / "pyproject.toml": _manifest(),
        types_py_root / "README.md": _README,
    }


def _strip_leading_docstring(source: str) -> str:
    """Remove the module-level docstring so the banner replaces it cleanly."""
    stripped = source.lstrip()
    if stripped.startswith('"""'):
        end = stripped.find('"""', 3)
        if end != -1:
            return stripped[end + 3 :].lstrip("\n")
    return source
