-- Governova Cloud — Stage 1, initial schema.
--
-- Generated by `prisma migrate diff --from-empty --to-schema-datamodel schema.prisma
-- --script` and committed verbatim. `ADR-015`: Prisma authors the schema and the
-- migrations, and `asyncpg` executes queries at runtime — so this SQL is the
-- artifact, and the tool that wrote it is not a runtime dependency.
--
-- Regenerating this file is a drift check, not a build step. `prisma migrate diff`
-- from these migrations to the schema must come back empty; a test asserts it.
--
-- Two constraints in here are the ones the credit ledger's correctness rests on,
-- and neither is enforceable in application code:
--
--   LedgerEntry_organisation_id_idempotency_key_key  a retried webhook cannot
--                                                    charge twice, because only
--                                                    the database sees both
--                                                    deliveries
--   LedgerEntry_organisation_id_seq_key              a hash chain cannot fork or
--                                                    repeat a position
--
-- And the composite foreign keys on TeamMembership make a team in one
-- organisation holding a membership from another *impossible* rather than merely
-- checked. `S14.8` records the denormalised column that buys that.
--
-- Every timestamp is TIMESTAMPTZ(6), and both halves of that are load-bearing.
-- Prisma's `DateTime` maps to `TIMESTAMP(3)` by default, which was what this
-- file said first and what the first run against a real PostgreSQL rejected:
--
--   no time zone      the column stores a wall-clock reading rather than an
--                     instant, and comes back naive. `canonical_timestamp`
--                     refuses a naive value, correctly — the column was wrong.
--
--   millisecond       `TIMESTAMP(3)` truncates the microseconds the ledger's
--   precision         hash is computed over. `...123456` stored as `...123`
--                     reads back `...123000`, which is a different string and a
--                     different hash. `verify()` would report a broken chain on
--                     data nobody touched.
--
-- `ADR-015` predicted the second one in writing before the column shipped
-- anyway. It was regenerated rather than altered because this migration had
-- never run outside a throwaway CI schema — after it runs anywhere real, this
-- becomes an ALTER that rewrites tamper-evidence.

-- CreateEnum
CREATE TYPE "OperatingMode" AS ENUM ('PERSONAL', 'TEAM', 'ENTERPRISE');

-- CreateEnum
CREATE TYPE "MemberRole" AS ENUM ('OWNER', 'ADMIN', 'MEMBER');

-- CreateEnum
CREATE TYPE "LedgerEntryKind" AS ENUM ('ACCRUAL', 'CONSUMPTION', 'GRANT', 'REFUND', 'EXPIRY');

-- CreateTable
CREATE TABLE "Account" (
    "id" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Organisation" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "mode" "OperatingMode" NOT NULL DEFAULT 'PERSONAL',
    "seats_purchased" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "Organisation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Membership" (
    "id" TEXT NOT NULL,
    "organisation_id" TEXT NOT NULL,
    "account_id" TEXT NOT NULL,
    "role" "MemberRole" NOT NULL DEFAULT 'MEMBER',
    "seat_assigned_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "Membership_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Team" (
    "id" TEXT NOT NULL,
    "organisation_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "Team_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TeamMembership" (
    "id" TEXT NOT NULL,
    "organisation_id" TEXT NOT NULL,
    "team_id" TEXT NOT NULL,
    "membership_id" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "TeamMembership_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LedgerEntry" (
    "id" TEXT NOT NULL,
    "organisation_id" TEXT NOT NULL,
    "seq" INTEGER NOT NULL,
    "kind" "LedgerEntryKind" NOT NULL,
    "amount_minor" BIGINT NOT NULL,
    "idempotency_key" TEXT NOT NULL,
    "occurred_at" TIMESTAMPTZ(6) NOT NULL,
    "detail" TEXT NOT NULL DEFAULT '',
    "prev_hash" TEXT NOT NULL,
    "record_hash" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LedgerEntry_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Account_subject_key" ON "Account"("subject");

-- CreateIndex
CREATE UNIQUE INDEX "Account_email_key" ON "Account"("email");

-- CreateIndex
CREATE INDEX "Account_deleted_at_idx" ON "Account"("deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "Organisation_slug_key" ON "Organisation"("slug");

-- CreateIndex
CREATE INDEX "Organisation_deleted_at_idx" ON "Organisation"("deleted_at");

-- CreateIndex
CREATE INDEX "Membership_organisation_id_idx" ON "Membership"("organisation_id");

-- CreateIndex
CREATE INDEX "Membership_account_id_idx" ON "Membership"("account_id");

-- CreateIndex
CREATE INDEX "Membership_deleted_at_idx" ON "Membership"("deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "Membership_organisation_id_account_id_key" ON "Membership"("organisation_id", "account_id");

-- CreateIndex
CREATE UNIQUE INDEX "Membership_organisation_id_id_key" ON "Membership"("organisation_id", "id");

-- CreateIndex
CREATE INDEX "Team_organisation_id_idx" ON "Team"("organisation_id");

-- CreateIndex
CREATE INDEX "Team_deleted_at_idx" ON "Team"("deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "Team_organisation_id_name_key" ON "Team"("organisation_id", "name");

-- CreateIndex
CREATE UNIQUE INDEX "Team_organisation_id_id_key" ON "Team"("organisation_id", "id");

-- CreateIndex
CREATE INDEX "TeamMembership_organisation_id_idx" ON "TeamMembership"("organisation_id");

-- CreateIndex
CREATE INDEX "TeamMembership_team_id_idx" ON "TeamMembership"("team_id");

-- CreateIndex
CREATE INDEX "TeamMembership_membership_id_idx" ON "TeamMembership"("membership_id");

-- CreateIndex
CREATE INDEX "TeamMembership_deleted_at_idx" ON "TeamMembership"("deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "TeamMembership_team_id_membership_id_key" ON "TeamMembership"("team_id", "membership_id");

-- CreateIndex
CREATE INDEX "LedgerEntry_organisation_id_idx" ON "LedgerEntry"("organisation_id");

-- CreateIndex
CREATE INDEX "LedgerEntry_occurred_at_idx" ON "LedgerEntry"("occurred_at");

-- CreateIndex
CREATE UNIQUE INDEX "LedgerEntry_organisation_id_idempotency_key_key" ON "LedgerEntry"("organisation_id", "idempotency_key");

-- CreateIndex
CREATE UNIQUE INDEX "LedgerEntry_organisation_id_seq_key" ON "LedgerEntry"("organisation_id", "seq");

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Team" ADD CONSTRAINT "Team_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TeamMembership" ADD CONSTRAINT "TeamMembership_organisation_id_team_id_fkey" FOREIGN KEY ("organisation_id", "team_id") REFERENCES "Team"("organisation_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TeamMembership" ADD CONSTRAINT "TeamMembership_organisation_id_membership_id_fkey" FOREIGN KEY ("organisation_id", "membership_id") REFERENCES "Membership"("organisation_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LedgerEntry" ADD CONSTRAINT "LedgerEntry_organisation_id_fkey" FOREIGN KEY ("organisation_id") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

